### PR TITLE
Fix maxperuser

### LINKED ISSUE #31: Exception thrown when maxPerUser is exceeded
I think this is a bug, although this behavior could be expected in some contexts.

## Expected behavior

When `maxPerUser` is exceeded, the captcha isn't saved in DB. The captcha shall then fail in every subsequent submit in the same session.

## Observed behavior

As soon as `maxPerUser` is exceeded, an exception is thrown with the message `Sth went wrong: Array`. The form can't be displayed any more.

## Cause

The MaxRule fails normally. Then, the saving operation fails normally too.
However, instead of displaying a simple flash error, `CaptchasTable::touch` throws a `BadMethodCallException` because `save()` method returned `false`.

This not only prevents bots to fill in the form any longer, but generates excessive error logs. If `maxPerUser` is set to a low value, human clients could also think that the site is down.
It would be better to display a smooth captcha error on submits.

### PR DESCRIPTION
**Pull request by zachee54**
Fixes #31 

## Purpose

When `maxPerUser`is exceeded, an exception is thrown unintentionally.
The expected behavior in this case could be to :

1. display the captcha. This may be desired in order to avoid lacks in the view, especially if the captcha is integrated in a sentence like _"What is the resuilt of...?"_
2. display a validation error indicating for instance _"too many attempts"_
3. fail on every form submission.

## How to do it

`MaxRule` has been changed from a _create_ rule to an _update_ rule.
This way, the captcha **can** be created by `CaptchasTable` but its result won't ever be saved by `PreparerComponent` when generating the image and its solution. `PreparerComponent` sets anyway the updated (and unsaved) captcha in the view so that it can be displayed in the view.

A new validation rule checks if the captcha's expected result is null, in which case it means that it will fail anyway on next submission. This is intended to display an error message, so that the user understands why every attempts are denied yet.

## Observation

Captchas were marked as used on success only. I think they should be marked as used on any attempt, because a new one will be generated on page reload.

### CODE REVIEW

**Comment by dereuromark** [comment]
We might need a test case for this, to also make sure this doesnt regress with future changes.
But looks good!

**Comment by dereuromark** [comment]
One of the main reasons the other PR doesnt want the first save to work out is to avoid having too many records being created by bots, flushing the DB with millions of entries etc.

**Comment by zachee54** [comment]
We can delete the captchas as soon as it is displayed, since it won't be used twice. So it frees the DB. I've just commited it.
That's inefficient if the bots don't load the image, though.

File: src/Controller/Component/PreparerComponent.php [hunk 1]
```diff
@@ -49,7 +49,17 @@ public function prepare($captcha) {
...
 
-		return $this->Captchas->save($captcha);
+		/*
+		 * Silently ignore saving failures, especially because of application rules.
+		 * This will result in the captcha to be displayed, but in the form
+		 * submission to fail intentionally since the expected result will still be
+		 * NULL.
+		 */
+		if (!$this->Captchas->save($captcha)) {
+			$this->Captchas->delete($captcha);  // Now useless if not updated
```
[the remark this answers is not in the document]
Comment (zachee54) [reply src/Controller/Component/PreparerComponent.php:59]: That's right !
However, if the limit is exceeded on this request, it will also be exceeded on next call.

File: src/Model/Behavior/CaptchaBehavior.php [hunk 2]
```diff
@@ -148,17 +158,35 @@ public function validateCaptchaMaxTime($value, $context) {
 	 *
 	 * @return bool
 	 */
-	public function validateCaptchaResult($value, $context) {
+	public function validateCaptchaMaxPerUser($value, $context) {
```
Comment (dereuromark) [inline src/Model/Behavior/CaptchaBehavior.php:161]: Where does it check here on the limit (e.g. 1000)?
So far it seems to be not triggering on flood limit.

Comment (zachee54) [reply src/Model/Behavior/CaptchaBehavior.php:161]: Although the limit is checked by `PreparerComponent::prepare()`, a validation rule is required on form submission request in order to display a related error message like _"Too many attemps"_. Without it, a human user who excesses the limit wouldn't ever know the reason why the form fails.

Comment (dereuromark) [reply src/Model/Behavior/CaptchaBehavior.php:161]: Hm, I tried your branch and somewhat I could always enter the captchas even after limit has been exceeded.
I guess because validateCaptchaMaxPerUser() gets the value still.

Comment (zachee54) [reply src/Model/Behavior/CaptchaBehavior.php:161]: It works for me.
The real switch is in `PreparerComponent::prepare()`. If the result isn't saved, you can't solve the captcha. This has nothing to do directly with `CaptchaBehavior::validateCaptchaMaxPerUser()`.
Did you test it in real conditions, I mean with captchas generated from the branch ?

Comment (dereuromark) [reply src/Model/Behavior/CaptchaBehavior.php:161]: Yes, and the message is solvable even after attempts for me, see sandbox locally to test

Comment (zachee54) [reply src/Model/Behavior/CaptchaBehavior.php:161]: What do you mean by _"sandbox locally"_ ?

Since you have the bug, can you debug it ? I don't know how to reproduce it.

Comment (dereuromark) [reply src/Model/Behavior/CaptchaBehavior.php:161]: As I wrote in the original ticket

    https://sandbox.dereuromark.de/sandbox/captchas/math?max=10

as local version checked out as

    http://sandbox.local/sandbox/captchas/math?max=10
    
can be used to test things locally.

I can take another look tomorrow.

Comment (zachee54) [reply src/Model/Behavior/CaptchaBehavior.php:161]: Sorry, I can't make sandbox run locally. I have an exception with `migrate` command
```PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `captcha`.`state_machine_item_states` (errno: 150 "Foreign key constraint is incorrectly formed") in /home/olivier/github/cakephp-sandbox/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192```

and then an exception on first run

`Could not locate bootstrap/dist/css/bootstrap.css for css-combined.css in any configured path.`

Comment (zachee54) [reply src/Model/Behavior/CaptchaBehavior.php:161]: > Hm, I tried your branch and somewhat I could always enter the captchas even after limit has been exceeded. I guess because validateCaptchaMaxPerUser() gets the value still.

Got it.
This is because the `?max=10` query param simply doesn't work.

There are 3 steps
1. The client loads the page. `max` query param may be given, and `maxPerUser` may be set dynamically. **However** no rule check is performed at this stage, so always OK.
2. The client loads the image. This request **has no query param**. Therefore, the former `max` value isn't taken in account, `maxPerUser`defaults to 1000 and captcha's secret is successfully generated (unless you test it 1000 times...).
3. The client submits the form. `CaptchaBehavior` checks whether the captcha exists or was deleted at step 2. Since it was updated successfully at previous step, the validation passes.

If you want to change `maxPerUser` dynamically, you must find a way to set the config value in the image load request. Sadly, this request bypasses the sandbox and triggers directly the captcha plugin.

Comment (dereuromark) [reply src/Model/Behavior/CaptchaBehavior.php:161]: Oh darn, you are right. It should then be part of the query string into the controller action for the image.
So indeed maybe not the best demo of it then :)

**Comment by zachee54** [comment]
I pushed a new commit to suggest checking `MaxRule` on page load instead of on image load request. It's more clear andcan be tested through the sandbox.

As a downside, the error message still relies on the inexistence of the captcha in the DB, which could technically be due to another cause. The message is also displayed only after form submission, and not directly on first page load.

**Comment by dereuromark** [comment]
Yeah, I now get side effects: If there is a limit, the sandbox demo now returns invalid value even for a valid answer instead of "Too many requests", hiding a bit the actual issue.
I wonder if we can make this a bit more stable somehow.

**Comment by dereuromark** [comment]
To some extend I am still leaning into the direction of https://github.com/dereuromark/cakephp-captcha/pull/32
If indeed the limit has been reached (which should never happen to normal users), maybe just not displaying anything is acceptable? Currently it throws an exception because it is something a normal user never ever should run into if configured appropriately, thus the exception being kind of acceptable.

**Comment by zachee54** [comment]
> Yeah, I now get side effects: If there is a limit, the sandbox demo now returns invalid value even for a valid answer instead of "Too many requests", hiding a bit the actual issue. I wonder if we can make this a bit more stable somehow.
> 
> To reproduce the last to be stored one needs to be "used", then the next ones generate this somehow.

I'm afraid I can't reproduce it. I always have _"Too many attempts"_ message.

**Comment by dereuromark** [comment]
Still a bit hesitant of the side effects this could bring.
I guess I could just merge it, since it should only affect bots, and very seldom actual users.

File: src/Controller/Component/PreparerComponent.php [hunk 3]
```diff
@@ -49,7 +49,15 @@ public function prepare($captcha) {
 			$captcha = $this->Captchas->patchEntity($captcha, $generated);
 		}
 
-		return $this->Captchas->save($captcha);
+		/*
+		 * If the captcha doesn't exist in DB, don't create it.
+		 * It will just be displayed as dummy challenge.
+		 */
+		if (!$captcha->isNew()) {
```
Comment (dereuromark) [inline src/Controller/Component/PreparerComponent.php:56]: Could this be the part that gives me the "always wrong" answer? Since it wouldnt match anything on validation, but the "max limit" isnt triggered in some cases?

**Comment by zachee54** [comment]
> To some extend I am still leaning into the direction of #32 If indeed the limit has been reached (which should never happen to normal users), maybe just not displaying anything is acceptable? Currently it throws an exception because it is something a normal user never ever should run into if configured appropriately, thus the exception being kind of acceptable.

I'm implementiing a contact form including approximately 100 possible contacts. Each user should use it at most 2 or 3 times in a normal way.
I also have a signup form. The former version was hacked by czech or russian users creating dozens of dummy accounts.

I want to protect these both forms with captchas. Not only to avoid bot spamming, but also to discourage human users to write to number of contacts, or to create dummy accounts.
Therefore, I'd want to set a low limit, like 20, or even lower because on the top of that the table is purged regularly according to `probability` parameter. Some users could then reach this limit in real life, and I'd prefer them not to become crazy because of a fake _"The solution is not correct"_ message.

But I'm hesitant too. Is it a fair use case, or am I trying to do too much for the plugin's purposes ?
What would be the desired behavior ? In my opinion :
- the form validation should fail (of course)
- the page shouldn't throw an exception in order not to fill the logs
- the overloaded captchas shouldn't be saved, in order not to fill the DB with dummies
- secondarily, the page shouldn't display an inappropriate message like _"The solution is not correct"_.

I think we got it in both #32 and #33 (just see my latest comment in #32). Just make it as simple as possible.

File: src/Controller/CaptchaController.php [hunk 4]
```diff
@@ -45,7 +46,11 @@ public function beforeFilter(EventInterface $event) {
 	 * @return \Cake\Http\Response|null|void
 	 */
 	public function display($id = null) {
-		$captcha = $this->Captchas->get($id);
+		if ($id === null) {
```
[the remark this answers is not in the document]
Comment (zachee54) [reply src/Controller/CaptchaController.php:49]: Yes, it could get millions of captchas. And yes, I don't see what they could do with.
Anyway, if you have enough motivation to use a text recognition engine, you can solve any captcha without having to gather millions of them. The plugin is just a first level shield.

File: src/Controller/Component/PreparerComponent.php (hunk 3 above)
Comment (zachee54) [reply src/Controller/Component/PreparerComponent.php:56]: I can't see how.
The max limit is checked only once per form. It lays in `CaptchasTable::touch()`, when the page is loaded at first.
The validation lays in `CaptchaBehavior`. It only checks whether the captcha exists in table.
Could `PreparerComponent` create the captcha itself in this snippet ? I think it can't since `$captcha->isNew()` tests exactly this.

BTW, I realise that `maxTime` validation rule must be checked *before* `maxPerUser`, because if `maxTime` is exceeded, the captcha might have been deleted by `cleanup()` in the meantime.

**Comment by dereuromark** [comment]
Yeah, sounds reasonable
I just wonder if your case would warrant more a feature flag and the default could/should still be failing harder.

But for simplicities' sake we can just move forward now, if this is working fully.

**Comment by dereuromark** [comment]
Bear in mind that using it this way (with such a low limit per user) should then also display a timeout of when it can be used again and a limit of purge
Otherwise displaying it would just be still very annoying regarding usability.

**Comment by dereuromark** [comment]
Maybe we should then also add a convenience method $this->Captcha->resetFor($this->AuthUser->id()); in component to allow resetting where needed, e.g. due to an extra kind of authentication step (two factor auth to allow resetting prior to 1h deadlock)?

**Comment by dereuromark** [comment]
I still have `The provided value is invalid` with tests for me in sandbox.. Weird.

**Comment by dereuromark** [comment]
I updated the sandbox accordingly with your changes
You can now see the same reproduced online: https://sandbox.dereuromark.de/sandbox/captchas/math

**Comment by dereuromark** [comment]
Hmm
the current way now also fails already with positivly entered ones
Like sandbox shows, if you enter 5 correct ones, the 6 will also say too many.
Not sure if this is intended..

**Comment by zachee54** [comment]
Just saw your latest changes.

> I still have `The provided value is invalid` with tests for me in sandbox - when sending nothing.. Weird.

This is because you didn't provide a customized message for `notBlank` rule. Nothing to do with the PR. I can fix it.

> With the correct answer I get `The solution is not correct`, since it was clearly a transient image (not stored captcha).

I still get _"Too many attempts"_ in this case. Strange.

> Hmm the current way now also fails already with positively entered ones Like sandbox shows, if you enter 5 correct ones, the 6 will also say too many. Not sure if this is intended..

> OK, this happened as used is now set also for wrongly used ones I excluded those now from the count. So that seems to work. The only downside is that you can now post many forms with random numbers. only displaying without sending is penalized.

> Overall I am not too happy yet with the `Too many attempts` validation rule, as it just means right now someone displayed too many forms without trying to post them with some value.

Ach... Genau.
As you said previously, there are two different features, and I realise that I'm mishandling by trying to implement both in the same one.
1. Prevent bots from submitting thousands of forms and randomly solving a captcha. Therefore, we track "unused" captchas, which are created for a short time, remain unsolved, but were possibly tried out with a wrong answer. **So wrong answered captchas musn't be marked as used**.
2. Prevent human users to send forms to dozens of contacts. Therefore we should track successfully answered captchas and block too active users, with a very low threshold. But it's off-topic : the captchas can't track such users since captcha's table is cleaned up randomly ; I should use a complete different system. Forget it.

Moreover, I realised that `maxPerUser` and `maxTime` validation rules both check the existence of the captcha. If the captcha doesn't exist, you can't decide whether it wasn't created due to `maxPerUser` or was cleaned up in the meanwhile because it was too old. So the error message may be irrelevant.

In conclusion, here is what I suggest :
- set a custom error message for `notBlank` validation rule.
- revert my changes in `CaptchaBehavior::validateCaptchaResult()` to let failed captchas as unused
- remove the `validateCaptchaMaxPerUser` validation rule. Since this is intended for bots, the error message doesn't matter. `validateCaptchaMaxTime()` will fail anyway in the same cases.
- plus : either set a lower default value for `maxPerUser` or get a higher complexity in `SimpleEngine`. In terms of probabilities, with `SimpleEngine`, a bot submitting 30 times a random result between 1 and 23 as a probablity of 61% to find at least one right answer out of the 30 attempts. The `SimpleEngine` is so simple that 1000 attempts is actually enough to submit dozens of forms successfully. In my opinion, such a breach is an unacceptable risk for the default engine.

**Comment by dereuromark** [comment]
I think now we are getting somewhere :)

Note that the default 1000 is just to make sure people configure it themselves to their needs without it blowing up in their face too early.
So sure, we can lower it a bit more, like 100?
But after all, it is an easy to set and document configuration value.

That said: I still think if you open up 100 forms and didnt post them, you should be able to do that, especially if some time passed (hours). So we still need to make sure there is a time threshold after which old ones are cleared and you are not deadlocked in actually then posting valid forms and anwers.

**Comment by zachee54** [comment]
I apologize for my misunderstanding. I wasted your time.

OK, we can lower default `maxPerUser` value to 100, and reset the count after 1 hour.
Instead of cleaning, I suggest that we simply limit the count scope according to `created` field in `getCount()`.
Should the 1-hour interval be configurable ?
